# Generated by Django 2.2.1 on 2019-05-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('custom_pk', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('talk_date', models.DateTimeField(verbose_name='Дата разговора:')),
                ('caller', models.CharField(max_length=11, verbose_name='Звонили с телефона:')),
                ('ans_caller', models.CharField(max_length=12, verbose_name='Звонили на телефон:')),
                ('call_direction', models.CharField(max_length=50, verbose_name='Направление:')),
                ('call_duration', models.IntegerField(verbose_name='Длительность звонка:')),
                ('money', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Сумма:')),
            ],
            options={
                'permissions': [('view_CallDetail', 'Can view /detail/ url')],
                'unique_together': {('talk_date', 'caller')},
            },
        ),
    ]
