# Generated by Django 2.2.1 on 2019-05-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_date', models.DateField(max_length=20, verbose_name='Дата разговора:')),
                ('caller', models.CharField(db_index=True, max_length=11, verbose_name='Звонили с телефона:')),
                ('ans_caller', models.CharField(db_index=True, max_length=12, verbose_name='Звонили на телефон:')),
                ('call_direction', models.CharField(max_length=50, verbose_name='Направление:')),
                ('call_duration', models.IntegerField(max_length=10, verbose_name='Длительность звонка:')),
                ('money', models.IntegerField(max_length=10, verbose_name='Сумма:')),
                ('talk_date_sec', models.DateTimeField(max_length=19, verbose_name='Дата разговора с секундами:')),
            ],
        ),
    ]
