# Generated by Django 2.2.1 on 2019-05-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='call_duration',
            field=models.IntegerField(verbose_name='Длительность звонка:'),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='money',
            field=models.IntegerField(verbose_name='Сумма:'),
        ),
    ]
