# Generated by Django 2.2.1 on 2019-05-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asu', '0002_auto_20190512_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calldetail',
            options={'permissions': [('view', 'Can view')]},
        ),
    ]
