# Generated by Django 2.2.1 on 2019-05-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asu', '0003_auto_20190512_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calldetail',
            options={},
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='money',
            field=models.CharField(max_length=11, verbose_name='Сумма:'),
        ),
    ]
