# Generated by Django 2.2.1 on 2019-05-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asu', '0006_remove_calldetail_talk_date_sec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='talk_date',
            field=models.CharField(max_length=20, verbose_name='Дата разговора:'),
        ),
    ]
