# Generated by Django 2.2.1 on 2019-05-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhonesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(db_index=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=11, unique=True)),
                ('dep_head', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
