# Generated by Django 2.2.1 on 2019-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneslist',
            name='dep_head',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ответственный за телефонный номер'),
        ),
        migrations.AlterField(
            model_name='phoneslist',
            name='org_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='phoneslist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Номер телефона'),
        ),
    ]
